import { KeyIcon, MinusIcon, PasswordIcon, PlusIcon } from "@phosphor-icons/react";
import { DisabledControl } from "../../components/DisabledControl";
import { SettingsCard } from "../../components/SettingsCard";
import { SettingsRow } from "../../components/SettingsRow";
import { ToggleSwitch } from "../../components/ToggleSwitch";
import { cx, settingsBorder, settingsMuted } from "../../lib/styles";

export function PrivacySettingsPage() {
  return (
    <>
      <SettingsCard>
        <SettingsRow note="Allow CopClip to appear to others when you share your screen." title="Show during screen sharing">
          <ToggleSwitch checked={false} label="Show during screen sharing" disabled />
        </SettingsRow>
        <SettingsRow note="Download web content for previews; may activate one-time or analytics-sensitive links." title="Generate link previews">
          <ToggleSwitch checked={false} label="Generate link previews" disabled />
        </SettingsRow>
      </SettingsCard>

      <SettingsCard>
        <SettingsRow note="Do not save passwords and sensitive data when detected." title="Ignore confidential content">
          <ToggleSwitch checked={false} label="Ignore confidential content" disabled />
        </SettingsRow>
        <SettingsRow note="Do not save temporary data generated by other apps." title="Ignore transient content">
          <ToggleSwitch checked={false} label="Ignore transient content" disabled />
        </SettingsRow>
      </SettingsCard>

      <h2 className="mx-3.5 -mb-2 mt-[18px] text-base font-bold tracking-[-0.02em] text-[#e8e8e8]">Ignore Applications</h2>
      <p className={cx("mx-3.5 -mt-2 text-xs leading-snug max-[560px]:text-sm", settingsMuted)}>Do not save content copied from the applications below.</p>
      <SettingsCard>
        <div className={cx("flex min-h-[52px] items-center gap-3 border-b px-3.5 py-2.5 text-sm font-semibold text-[#e8e8e8]", settingsBorder)}><KeyIcon aria-hidden="true" className="h-8 w-8 rounded-lg bg-[#303333] p-1.5 text-[#c8c8c8]" weight="duotone" />Keychain Access</div>
        <div className={cx("flex min-h-[52px] items-center gap-3 border-b px-3.5 py-2.5 text-sm font-semibold text-[#e8e8e8]", settingsBorder)}><PasswordIcon aria-hidden="true" className="h-8 w-8 rounded-lg bg-[#303333] p-1.5 text-[#ffd449]" weight="duotone" />Passwords</div>
        <div className="flex gap-px bg-[#303333] px-2.5 py-1.5" aria-label="Ignored application actions">
          <DisabledControl label="Adding ignored apps is planned"><PlusIcon aria-hidden="true" size={14} weight="bold" /></DisabledControl>
          <DisabledControl label="Removing ignored apps is planned"><MinusIcon aria-hidden="true" size={14} weight="bold" /></DisabledControl>
        </div>
      </SettingsCard>
    </>
  );
}
